"""Generate the local staging stack's secrets, once.

Writes `.env` (read by `compose.yml`) and `keys/` (the RS256 pair the API signs
access tokens with). Both are gitignored. Nothing in the stack uses a
development default: `ENVIRONMENT=production` refuses to boot on one
(`app.config.assert_production_safe`), which is part of what is being tested.

Run with the backend's virtualenv, which has `cryptography`:

    backend/.venv/bin/python deploy/local-staging/gen_secrets.py

Existing files are left alone; delete them to rotate.
"""

import secrets
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

HERE = Path(__file__).resolve().parent


def _token() -> str:
    return secrets.token_urlsafe(32)


def main() -> None:
    env = HERE / ".env"
    if env.exists():
        print(f"kept {env}")
    else:
        env.write_text(
            "\n".join(
                [
                    "# Generated by gen_secrets.py — local staging only, never committed.",
                    f"POSTGRES_PASSWORD={_token()}",
                    f"REDIS_PASSWORD={_token()}",
                    "MINIO_ROOT_USER=staging-root",
                    f"MINIO_ROOT_PASSWORD={_token()}",
                    "S3_ACCESS_KEY_ID=zipzop-app",
                    f"S3_SECRET_ACCESS_KEY={_token()}",
                    f"JWT_SECRET_KEY={_token()}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        print(f"wrote {env}")

    keys = HERE / "keys"
    private = keys / "jwt_private.pem"
    if private.exists():
        print(f"kept {keys}")
        return
    keys.mkdir(exist_ok=True)
    key = rsa.generate_private_key(public_exponent=65537, key_size=3072)
    private.write_bytes(
        key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    (keys / "jwt_public.pem").write_bytes(
        key.public_key().public_bytes(
            serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
        )
    )
    print(f"wrote {keys}")


if __name__ == "__main__":
    main()
