"""Column patterns shared by every table."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKey:
    """UUID primary keys throughout.

    Generated by the database so an insert never has to round-trip first, and
    unguessable so an id in a URL leaks nothing about volume or ordering.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """created_at / updated_at, both maintained by the database.

    Server-side defaults rather than Python ones, so a row written by a
    migration or by psql gets the same treatment as one written by the app.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """deleted_at for anything a user can remove.

    Soft delete first, hard delete on a schedule — a user who deletes a project
    by accident has a window, and account deletion cascades properly later
    (docs/diagrams/data-model.md §3).
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )
