"""M2 — accounts, media, projects, jobs and the money tables

Every table from docs/03-backend-architecture.md §4.2, in the order that
document lists them, plus the four seeded plans from §5.5.

Written by hand rather than autogenerated. Autogenerate gets three things wrong
here and each one is silent: it re-creates native enum types that a column
already installed, it drops the `postgresql_where` from partial indexes, and it
cannot order the two circular foreign keys between `media_assets` and `jobs`.

M2 uses `users`, `refresh_tokens`, `media_assets`, `plans`, `subscriptions` and
`credit_ledger`. The rest are created now because registration has to grant a
plan allowance in one transaction, and because a half-built schema is worse to
migrate than a complete one.

Revision ID: 0002_m2_schema
Revises: 0001_baseline
Create Date: 2026-08-16

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.models.enums import ENUM_TYPES, enum_labels

revision: str = "0002_m2_schema"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str) -> postgresql.ENUM:
    """Reference a type this migration already created.

    `create_type=False` matters: without it every column that mentions the type
    tries to CREATE TYPE again and the second table fails.
    """
    return postgresql.ENUM(name=name, create_type=False)


def upgrade() -> None:
    # ---------------------------------------------------------------- enums
    for type_name, python_enum in ENUM_TYPES:
        labels = ", ".join(f"'{label}'" for label in enum_labels(python_enum))
        op.execute(f"CREATE TYPE {type_name} AS ENUM ({labels})")

    # ---------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("status", _enum("user_status"), server_default="active", nullable=False),
        sa.Column("plan_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("topup_credits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("facemap_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("storage_bytes_used", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("plan_credits >= 0", name="plan_credits_non_negative"),
        sa.CheckConstraint("topup_credits >= 0", name="topup_credits_non_negative"),
        sa.CheckConstraint("facemap_seconds >= 0", name="facemap_seconds_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # ------------------------------------------------------- refresh_tokens
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_refresh_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["refresh_tokens.id"],
            name="fk_refresh_tokens_replaced_by_refresh_tokens",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index(
        "ix_refresh_tokens_user_id_live",
        "refresh_tokens",
        ["user_id"],
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # -------------------------------------------------------- media_assets
    op.create_table(
        "media_assets",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", _enum("asset_kind"), nullable=False),
        sa.Column("status", _enum("asset_status"), server_default="pending_upload", nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("proxy_key", sa.Text(), nullable=True),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("peaks_key", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum_sha256", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Numeric(7, 3), nullable=True),
        sa.Column("video_codec", sa.Text(), nullable=True),
        sa.Column("audio_codec", sa.Text(), nullable=True),
        sa.Column("audio_channels", sa.SmallInteger(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("derived_from_asset_id", postgresql.UUID(as_uuid=True), nullable=True),
        # The FK on this one is added after `jobs` exists.
        sa.Column("derived_by_job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_media_assets_user_id_users", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["derived_from_asset_id"],
            ["media_assets.id"],
            name="fk_media_assets_derived_from_asset_id_media_assets",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_media_assets"),
    )
    op.create_index(
        "ix_media_assets_user_id_created_at",
        "media_assets",
        ["user_id", sa.text("created_at DESC")],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_media_assets_derived_from_asset_id",
        "media_assets",
        ["derived_from_asset_id"],
        postgresql_where=sa.text("derived_from_asset_id IS NOT NULL"),
    )
    op.create_index(
        "ix_media_assets_user_id_checksum_sha256",
        "media_assets",
        ["user_id", "checksum_sha256"],
        postgresql_where=sa.text("status = 'ready'"),
    )

    # ------------------------------------------------------------ projects
    op.create_table(
        "projects",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.Text(), server_default="Untitled project", nullable=False),
        sa.Column("aspect_ratio", sa.Text(), server_default="9:16", nullable=False),
        sa.Column("width", sa.Integer(), server_default="1080", nullable=False),
        sa.Column("height", sa.Integer(), server_default="1920", nullable=False),
        sa.Column("fps", sa.SmallInteger(), server_default="30", nullable=False),
        sa.Column(
            "timeline",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{\"tracks\": []}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_projects_user_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_projects"),
    )
    op.create_index(
        "ix_projects_user_id_updated_at",
        "projects",
        ["user_id", sa.text("updated_at DESC")],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ------------------------------------------------------ project_assets
    op.create_table(
        "project_assets",
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_project_assets_project_id_projects",
            ondelete="CASCADE",
        ),
        # RESTRICT, deliberately: an asset a project still uses cannot be
        # deleted out from under it. The API turns this into ASSET_IN_USE.
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["media_assets.id"],
            name="fk_project_assets_asset_id_media_assets",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("project_id", "asset_id", name="pk_project_assets"),
    )
    op.create_index("ix_project_assets_asset_id", "project_assets", ["asset_id"])

    # ---------------------------------------------------------------- jobs
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("tool", _enum("job_tool"), nullable=False),
        sa.Column("family", _enum("job_family"), nullable=False),
        sa.Column("status", _enum("job_status"), server_default="queued", nullable=False),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_key", sa.Text(), nullable=True),
        sa.Column("output_asset_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("credits_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("credits_settled", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="progress_is_a_percentage"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_jobs_user_id_users", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_jobs_project_id_projects", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["output_asset_id"],
            ["media_assets.id"],
            name="fk_jobs_output_asset_id_media_assets",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_jobs"),
    )
    op.create_index(
        "uq_jobs_user_id_idempotency_key",
        "jobs",
        ["user_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index("ix_jobs_user_id_created_at", "jobs", ["user_id", sa.text("created_at DESC")])
    op.create_index(
        "ix_jobs_project_id",
        "jobs",
        ["project_id"],
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        "ix_jobs_status_live",
        "jobs",
        ["status"],
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )

    # The second half of the media_assets <-> jobs cycle.
    op.create_foreign_key(
        "fk_media_assets_derived_by_job_id_jobs",
        "media_assets",
        "jobs",
        ["derived_by_job_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # --------------------------------------------------------------- plans
    op.create_table(
        "plans",
        sa.Column("code", _enum("plan_code"), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("monthly_credits", sa.Integer(), nullable=False),
        sa.Column("facemap_seconds", sa.Integer(), nullable=False),
        sa.Column("fair_use_credits", sa.Integer(), nullable=True),
        sa.Column("max_export_height", sa.Integer(), nullable=False),
        sa.Column("watermark", _enum("watermark_mode"), nullable=False),
        sa.Column("queue_priority", sa.SmallInteger(), nullable=False),
        sa.Column("price_usd_cents", sa.Integer(), nullable=True),
        sa.Column("price_inr_paise", sa.Integer(), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name="pk_plans"),
    )

    # ------------------------------------------------------- subscriptions
    op.create_table(
        "subscriptions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("plan", _enum("plan_code"), nullable=False),
        sa.Column("status", _enum("sub_status"), server_default="active", nullable=False),
        sa.Column("provider", _enum("payment_provider"), nullable=True),
        sa.Column("provider_customer_id", sa.Text(), nullable=True),
        sa.Column("provider_subscription_id", sa.Text(), nullable=True),
        sa.Column("currency", sa.CHAR(3), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_subscriptions_user_id_users", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["plan"], ["plans.code"], name="fk_subscriptions_plan_plans"),
        sa.PrimaryKeyConstraint("id", name="pk_subscriptions"),
    )
    op.create_index(
        "one_live_subscription",
        "subscriptions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('active', 'past_due')"),
    )
    op.create_index(
        "uq_subscriptions_provider_provider_subscription_id",
        "subscriptions",
        ["provider", "provider_subscription_id"],
        unique=True,
        postgresql_where=sa.text("provider_subscription_id IS NOT NULL"),
    )
    op.create_index(
        "ix_subscriptions_current_period_end",
        "subscriptions",
        ["current_period_end"],
        postgresql_where=sa.text("status IN ('active', 'past_due')"),
    )

    # ------------------------------------------------------------ payments
    op.create_table(
        "payments",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subscription_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("provider", _enum("payment_provider"), nullable=False),
        sa.Column("provider_payment_id", sa.Text(), nullable=False),
        sa.Column("kind", _enum("payment_kind"), nullable=False),
        sa.Column("status", _enum("payment_status"), server_default="pending", nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.CHAR(3), nullable=False),
        sa.Column("credits_granted", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_payments_user_id_users", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name="fk_payments_subscription_id_subscriptions",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_payments"),
    )
    op.create_index(
        "uq_payments_provider_provider_payment_id",
        "payments",
        ["provider", "provider_payment_id"],
        unique=True,
    )

    # ----------------------------------------------------- provider_events
    op.create_table(
        "provider_events",
        sa.Column("provider", _enum("payment_provider"), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("provider", "event_id", name="pk_provider_events"),
    )

    # ------------------------------------------------------- credit_ledger
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("bucket", _enum("credit_bucket"), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", _enum("ledger_reason"), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("delta <> 0", name="delta_is_never_zero"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_credit_ledger_user_id_users", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="fk_credit_ledger_job_id_jobs", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name="fk_credit_ledger_payment_id_payments",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_credit_ledger"),
    )
    op.create_index(
        "ix_credit_ledger_user_id_created_at",
        "credit_ledger",
        ["user_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "uq_credit_ledger_job_id_reason_bucket",
        "credit_ledger",
        ["job_id", "reason", "bucket"],
        unique=True,
        postgresql_where=sa.text("job_id IS NOT NULL"),
    )

    # ------------------------------------------------------- the plan seed
    # Values from docs/03-backend-architecture.md §5.5. The credit numbers are
    # a proposal to be recalibrated on measured cost-per-job; the ratios are
    # not. Kept as data so a repricing is an UPDATE, not a deploy.
    op.execute(
        """
        INSERT INTO plans (
            code, display_name, monthly_credits, facemap_seconds, fair_use_credits,
            max_export_height, watermark, queue_priority, price_usd_cents, price_inr_paise
        ) VALUES
            ('free',     'Free',       300,    0,  NULL,   720, 'forced',  0,  NULL,   NULL),
            ('pro',      'Pro',       2500,  300,  NULL,  1080, 'none',   10,  1999,  99900),
            ('business', 'Business',  8000, 1200,  NULL,  2160, 'none',   20,  4999, 199900),
            ('studio',   'Studio',   30000, 3600, 30000,  2160, 'custom', 30,  9999, 299900)
        """
    )


def downgrade() -> None:
    # Tables first, in reverse dependency order, then the types they used.
    op.drop_table("credit_ledger")
    op.drop_table("provider_events")
    op.drop_table("payments")
    op.drop_table("subscriptions")
    op.drop_table("plans")
    # Break the cycle before dropping either side of it.
    op.drop_constraint("fk_media_assets_derived_by_job_id_jobs", "media_assets", type_="foreignkey")
    op.drop_table("jobs")
    op.drop_table("project_assets")
    op.drop_table("projects")
    op.drop_table("media_assets")
    op.drop_table("refresh_tokens")
    op.drop_table("users")

    for type_name, _python_enum in reversed(ENUM_TYPES):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
