"""Public identifiers.

The database stores bare UUIDs. The API exposes them prefixed —
`usr_…`, `ast_…`, `prj_…` — because the contract says so
(docs/05-api-contract.md §1: "Identifiers are UUIDs, prefixed in responses for
readability. The prefix is part of the string.").

The prefix is not decoration. It makes a mis-wired client fail loudly: passing
a project id where an asset id belongs is a 404 with a clear message instead of
a lookup that silently finds nothing, and a support ticket quoting an id says
what kind of thing it is without a database round trip.

**Format:** `<prefix>_<canonical lowercase UUID with dashes>`, e.g.
`usr_9b1d0c4e-3f2a-4c81-9d77-2e6b5a1f0c34`. The contract's examples are
truncated (`usr_9b1d…`) and do not pin this down, so it is fixed here and
documented rather than left to each caller to guess.
"""

import uuid
from typing import Final

from app.api.errors import NotFoundError

USER: Final = "usr"
ASSET: Final = "ast"
PROJECT: Final = "prj"
JOB: Final = "job"
PAYMENT: Final = "pay"
#: Clip and track ids (`clp_`, `trk_`) are generated by the client inside the
#: timeline document and never round-trip through this module.


def encode(prefix: str, value: uuid.UUID) -> str:
    return f"{prefix}_{value}"


def decode(prefix: str, value: str) -> uuid.UUID:
    """Parse a public id, or raise 404.

    404 rather than 422 on a malformed id: to the caller there is no difference
    between "this id is nonsense" and "this id names something you cannot see",
    and telling them apart would leak whether an id exists.
    """
    expected = f"{prefix}_"
    if not value.startswith(expected):
        raise NotFoundError()
    try:
        return uuid.UUID(value[len(expected) :])
    except ValueError:
        raise NotFoundError() from None
